# Site
name: "Moustafa Blog"
description: "A Blog about drones and AI"
meta_description: "Made by Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-126702263-1'
disqus: 'demowebsite'
mailchimp-list: 'https://github.us19.list-manage.com/subscribe/post?u=90627041a689be0cae94cec69&amp;id=681d6bb9fa'

# Authors
authors:
  mou:
    name: Mou
    display_name: Moustafa Abdelhamid
    gravatar: d72d2b17791e9b5b7399f1046118ea51
    email: mou.abdelhamid@gmail.com
    web: https://dosht.github.io/
    twitter: https://twitter.com/dosht
    description: "Machine Learning Engineer"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge