#!/bin/bash

echo "Creating a new post."

read -p "Titie: " post_title

post_slug=$(echo $post_title | awk '{print tolower($0)}' | sed --expression='s/\ /-/g' | sed 's/[^a-zA-Z0-9\-]//g')
echo "Slug: $post_slug"

read -e -p "Date: " -i $(date +'%Y-%m-%d') post_date
read -e -p "featured: " -i "true" featured
read -e -p "sitemap: " -i "true" sitemap
read -e -p "hidden: " -i "false" hidden
read -p "tags: " tags

post_name="$post_date-$post_slug"
file_path="_posts/$post_name.md"
cover_file_path="assets/images/$post_name.jpg"
branch_name="post/$post_name"

git co -b $branch_name

cat >> $file_path << EOF
---
layout: post
title:  "$post_title"
author: mou
categories: [ $tags ]
image: $cover_file_path
featured: $featured
hidden: $hidden
sitemap: $sitemap
---
EOF

git add $file_path
git ci -m "Create post $post_title"
